import type { Chapter, Question } from "./types";

// ---------------------------------------------------------------------------
// CLASS 6 MATHS — full chapter set with lessons.
// A merged, comprehensive coverage of the current NCERT "Ganita Prakash"
// (2025–26) and the classic NCERT Class 6 Maths concepts. Each chapter teaches
// the concepts (lesson) before its practice questions. The Integers chapter
// lives in seed.ts; everything else is here. Spread into CHAPTERS / QUESTIONS
// by seed.ts.
// ---------------------------------------------------------------------------

const C6 = { classId: "6", subjectId: "maths" } as const;

export const C6_MATH_CHAPTERS: Chapter[] = [
  {
    ...C6,
    id: "6-maths-knowing-our-numbers",
    title: "Knowing Our Numbers",
    blurb: "Place value, large numbers, comparing, estimation and Roman numerals.",
    ncertRef: "NCERT Class 6 Maths — Knowing Our Numbers",
    lesson: [
      { kind: "heading", text: "Comparing numbers" },
      {
        kind: "para",
        text: "To compare two numbers, first count their digits — the number with more digits is greater. If they have the same number of digits, compare from the leftmost (highest place value) digit.",
      },
      { kind: "heading", text: "Place value" },
      {
        kind: "para",
        text: "In the Indian system, places go ones, tens, hundreds, thousands, ten-thousands, lakhs, ten-lakhs, crores. In the International system they go ones, tens, hundreds, thousands, then millions.",
      },
      {
        kind: "example",
        problem: "What is the place value of 7 in 4,73,521?",
        solution: "7 is in the ten-thousands place, so its place value is 7 × 10,000 = 70,000.",
      },
      { kind: "heading", text: "Estimation (rounding)" },
      {
        kind: "para",
        text: "Estimating means rounding to the nearest 10, 100 or 1000 to get a quick, approximate answer. Look at the digit to the right of the rounding place: 5 or more rounds up, less than 5 rounds down.",
      },
      { kind: "tip", text: "Use commas to group digits — it makes large numbers far easier to read." },
      { kind: "heading", text: "Roman numerals" },
      {
        kind: "list",
        items: [
          "I = 1, V = 5, X = 10, L = 50, C = 100, D = 500, M = 1000.",
          "A smaller symbol AFTER a larger one adds (VI = 6); BEFORE a larger one subtracts (IV = 4).",
          "A symbol is never repeated more than three times.",
        ],
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-whole-numbers",
    title: "Whole Numbers",
    blurb: "The number line, successor/predecessor, and properties of operations.",
    ncertRef: "NCERT Class 6 Maths — Whole Numbers",
    lesson: [
      { kind: "heading", text: "Natural and whole numbers" },
      {
        kind: "para",
        text: "Counting numbers 1, 2, 3, … are natural numbers. Adding 0 to them gives the whole numbers: 0, 1, 2, 3, … Every whole number has a successor (the next one); every whole number except 0 has a predecessor (the one before).",
      },
      { kind: "heading", text: "The number line" },
      {
        kind: "para",
        text: "On a number line, addition means jumping to the right and subtraction means jumping to the left. Multiplication is repeated jumps of equal size.",
      },
      { kind: "heading", text: "Properties of operations" },
      {
        kind: "list",
        items: [
          "Commutative: order doesn't matter for + and × (a + b = b + a; a × b = b × a).",
          "Associative: grouping doesn't matter for + and × .",
          "Distributive: a × (b + c) = a × b + a × c.",
          "Identity: 0 is the additive identity (a + 0 = a); 1 is the multiplicative identity (a × 1 = a).",
        ],
      },
      { kind: "tip", text: "Division by 0 is not defined — you cannot share something among zero groups." },
    ],
  },
  {
    ...C6,
    id: "6-maths-patterns",
    title: "Patterns in Mathematics",
    blurb: "Number sequences, triangular and square numbers, and shape patterns.",
    ncertRef: "NCERT Class 6 Maths (Ganita Prakash) — Patterns in Mathematics",
    lesson: [
      { kind: "heading", text: "Spotting a pattern" },
      {
        kind: "para",
        text: "A pattern is a rule that tells you how a sequence continues. Find the rule by checking what is added, subtracted or multiplied each step.",
      },
      {
        kind: "example",
        problem: "Find the next number: 2, 5, 8, 11, …",
        solution: "Each term increases by 3, so the next is 11 + 3 = 14.",
      },
      { kind: "heading", text: "Special number patterns" },
      {
        kind: "list",
        items: [
          "Triangular numbers: 1, 3, 6, 10, 15 … (dots that form triangles; each adds the next counting number).",
          "Square numbers: 1, 4, 9, 16, 25 … (n × n).",
          "Odd numbers add up to square numbers: 1 + 3 = 4, 1 + 3 + 5 = 9.",
        ],
      },
      { kind: "tip", text: "When stuck, write the differences between terms — the differences often reveal the rule." },
    ],
  },
  {
    ...C6,
    id: "6-maths-number-play",
    title: "Number Play",
    blurb: "Playing with digits — palindromes, digit sums and number puzzles.",
    ncertRef: "NCERT Class 6 Maths (Ganita Prakash) — Number Play",
    lesson: [
      { kind: "heading", text: "Reading numbers in fun ways" },
      {
        kind: "para",
        text: "Numbers hide many patterns. A palindrome reads the same forwards and backwards, like 121 or 4554. The digit sum is found by adding all the digits (the digit sum of 142 is 1 + 4 + 2 = 7).",
      },
      { kind: "heading", text: "Why digit sums are useful" },
      {
        kind: "para",
        text: "Digit sums help check divisibility: if the digit sum is divisible by 3, the number is divisible by 3; if by 9, the number is divisible by 9.",
      },
      {
        kind: "example",
        problem: "Is 234 divisible by 3?",
        solution: "Digit sum = 2 + 3 + 4 = 9, which is divisible by 3, so yes — 234 is divisible by 3.",
      },
      { kind: "tip", text: "Make the largest number from given digits by placing the biggest digit on the left." },
    ],
  },
  {
    ...C6,
    id: "6-maths-playing-with-numbers",
    title: "Playing with Numbers (Prime Time)",
    blurb: "Factors, multiples, primes, divisibility rules, HCF and LCM.",
    ncertRef: "NCERT Class 6 Maths — Playing with Numbers / Prime Time",
    lesson: [
      { kind: "heading", text: "Factors and multiples" },
      {
        kind: "para",
        text: "A factor of a number divides it exactly (no remainder). A multiple is the result of multiplying a number by 1, 2, 3, … For example, factors of 12 are 1, 2, 3, 4, 6, 12; multiples of 5 are 5, 10, 15, 20 …",
      },
      { kind: "heading", text: "Prime and composite numbers" },
      {
        kind: "list",
        items: [
          "A prime number has exactly two factors: 1 and itself (2, 3, 5, 7, 11 …).",
          "A composite number has more than two factors (4, 6, 8, 9 …).",
          "1 is neither prime nor composite. 2 is the only even prime.",
        ],
      },
      { kind: "heading", text: "Divisibility rules" },
      {
        kind: "list",
        items: [
          "By 2: last digit is even (0,2,4,6,8).",
          "By 3: digit sum divisible by 3.",
          "By 5: last digit is 0 or 5.",
          "By 9: digit sum divisible by 9.",
          "By 10: last digit is 0.",
        ],
      },
      { kind: "heading", text: "HCF and LCM" },
      {
        kind: "para",
        text: "The HCF (Highest Common Factor) is the largest number that divides two numbers. The LCM (Lowest Common Multiple) is the smallest number that both divide into.",
      },
      {
        kind: "example",
        problem: "Find the HCF and LCM of 12 and 18.",
        solution:
          "12 = 2×2×3, 18 = 2×3×3. HCF = common factors = 2×3 = 6. LCM = 2×2×3×3 = 36.",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-basic-geometrical-ideas",
    title: "Basic Geometrical Ideas",
    blurb: "Points, lines, rays, curves, polygons and parts of a circle.",
    ncertRef: "NCERT Class 6 Maths — Basic Geometrical Ideas",
    lesson: [
      { kind: "heading", text: "The building blocks" },
      {
        kind: "list",
        items: [
          "Point: an exact location, with no size.",
          "Line segment: the shortest path between two points (has two endpoints).",
          "Ray: starts at a point and goes on forever in one direction.",
          "Line: extends forever in both directions.",
        ],
      },
      { kind: "heading", text: "Lines that meet — or don't" },
      {
        kind: "para",
        text: "Two lines that cross are intersecting lines; the point where they meet is the point of intersection. Lines that never meet, staying the same distance apart, are parallel lines.",
      },
      { kind: "heading", text: "Curves and polygons" },
      {
        kind: "para",
        text: "A closed figure made only of line segments is a polygon. Its segments are sides, the corners are vertices, and the turn at each corner is an angle. A triangle has 3 sides, a quadrilateral 4.",
      },
      { kind: "heading", text: "Parts of a circle" },
      {
        kind: "list",
        items: [
          "Centre: the middle point.",
          "Radius: centre to any point on the circle.",
          "Diameter: across the circle through the centre (= 2 × radius).",
          "Chord: a segment joining two points on the circle.",
        ],
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-lines-and-angles",
    title: "Lines and Angles",
    blurb: "Types of angles, measuring with a protractor, and angle pairs.",
    ncertRef: "NCERT Class 6 Maths (Ganita Prakash) — Lines and Angles",
    lesson: [
      { kind: "heading", text: "What is an angle?" },
      {
        kind: "para",
        text: "An angle is formed when two rays meet at a common endpoint (the vertex). Angles are measured in degrees (°) using a protractor.",
      },
      { kind: "heading", text: "Types of angles" },
      {
        kind: "list",
        items: [
          "Acute: less than 90°.",
          "Right: exactly 90°.",
          "Obtuse: between 90° and 180°.",
          "Straight: exactly 180°.",
          "Reflex: between 180° and 360°.",
        ],
      },
      { kind: "heading", text: "Pairs of angles" },
      {
        kind: "list",
        items: [
          "Complementary angles add up to 90°.",
          "Supplementary angles add up to 180°.",
        ],
      },
      {
        kind: "example",
        problem: "An angle is 35°. What is its complement?",
        solution: "Complement = 90° − 35° = 55°.",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-elementary-shapes",
    title: "Understanding Elementary Shapes",
    blurb: "Triangles, quadrilaterals and 3-D solids (faces, edges, vertices).",
    ncertRef: "NCERT Class 6 Maths — Understanding Elementary Shapes",
    lesson: [
      { kind: "heading", text: "Triangles" },
      {
        kind: "list",
        items: [
          "By sides: equilateral (all equal), isosceles (two equal), scalene (all different).",
          "By angles: acute, right, or obtuse triangle.",
          "The three angles of any triangle always add up to 180°.",
        ],
      },
      { kind: "heading", text: "Quadrilaterals" },
      {
        kind: "para",
        text: "A four-sided figure. Special ones include the square, rectangle, parallelogram, rhombus and trapezium. The angles of a quadrilateral add up to 360°.",
      },
      { kind: "heading", text: "3-D shapes" },
      {
        kind: "para",
        text: "Solids have faces (flat surfaces), edges (where faces meet) and vertices (corners). A cube has 6 faces, 12 edges and 8 vertices.",
      },
      { kind: "tip", text: "A cuboid is like a stretched cube — also 6 faces, 12 edges, 8 vertices." },
    ],
  },
  {
    ...C6,
    id: "6-maths-fractions",
    title: "Fractions",
    blurb: "Types of fractions, equivalent fractions, comparing and operations.",
    ncertRef: "NCERT Class 6 Maths — Fractions",
    lesson: [
      { kind: "heading", text: "What a fraction means" },
      {
        kind: "para",
        text: "A fraction shows part of a whole. In 3/4, the bottom number (denominator) is the number of equal parts the whole is split into, and the top (numerator) is how many we take.",
      },
      { kind: "heading", text: "Types of fractions" },
      {
        kind: "list",
        items: [
          "Proper: numerator < denominator (e.g. 3/5).",
          "Improper: numerator ≥ denominator (e.g. 7/4).",
          "Mixed: a whole number with a proper fraction (e.g. 1¾).",
        ],
      },
      { kind: "heading", text: "Equivalent fractions" },
      {
        kind: "para",
        text: "Multiplying or dividing the numerator and denominator by the same number gives an equivalent fraction: 1/2 = 2/4 = 3/6. Dividing to the smallest form gives the simplest (lowest) terms.",
      },
      { kind: "heading", text: "Adding and subtracting" },
      {
        kind: "para",
        text: "With the same denominator, just add/subtract the numerators. With different denominators, first rewrite them with a common denominator (the LCM of the denominators).",
      },
      {
        kind: "example",
        problem: "Add 1/4 + 2/4.",
        solution: "Same denominator: add numerators → (1 + 2)/4 = 3/4.",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-decimals",
    title: "Decimals",
    blurb: "Tenths and hundredths, place value, and converting with fractions.",
    ncertRef: "NCERT Class 6 Maths — Decimals",
    lesson: [
      { kind: "heading", text: "Decimal place value" },
      {
        kind: "para",
        text: "A decimal point separates the whole part from the fractional part. The first digit after the point is tenths (1/10), the second is hundredths (1/100), and so on.",
      },
      { kind: "heading", text: "Fractions ↔ decimals" },
      {
        kind: "list",
        items: [
          "1/10 = 0.1, 1/100 = 0.01.",
          "To write a fraction with denominator 10/100 as a decimal, just place the digits after the point: 7/10 = 0.7, 23/100 = 0.23.",
        ],
      },
      { kind: "heading", text: "Adding and subtracting decimals" },
      {
        kind: "para",
        text: "Line up the decimal points, then add or subtract as usual. Money and lengths use decimals every day (₹12.50, 1.75 m).",
      },
      {
        kind: "example",
        problem: "Write 3/4 as a decimal.",
        solution: "3/4 = 75/100 = 0.75.",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-data-handling",
    title: "Data Handling and Presentation",
    blurb: "Collecting data, tally marks, pictographs and bar graphs.",
    ncertRef: "NCERT Class 6 Maths — Data Handling and Presentation",
    lesson: [
      { kind: "heading", text: "What is data?" },
      {
        kind: "para",
        text: "Data is a collection of information, usually numbers. To make it useful we organise and picture it so patterns are easy to see.",
      },
      { kind: "heading", text: "Ways to show data" },
      {
        kind: "list",
        items: [
          "Tally marks: group counts in fives (four lines crossed by a fifth).",
          "Pictograph: uses a symbol to stand for a number of items.",
          "Bar graph: bars whose heights show the values.",
        ],
      },
      { kind: "tip", text: "Always read the key of a pictograph — one picture might stand for 5 or 10 items, not 1." },
      {
        kind: "example",
        problem: "In a pictograph, ⭐ = 10 books. How many books do 4 stars show?",
        solution: "4 × 10 = 40 books.",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-mensuration",
    title: "Perimeter and Area (Mensuration)",
    blurb: "Perimeter and area of rectangles, squares and simple shapes.",
    ncertRef: "NCERT Class 6 Maths — Perimeter and Area / Mensuration",
    lesson: [
      { kind: "heading", text: "Perimeter" },
      {
        kind: "para",
        text: "Perimeter is the total distance around the boundary of a flat shape — add up all the side lengths.",
      },
      { kind: "formula", text: "Perimeter of rectangle = 2 × (length + breadth)    Perimeter of square = 4 × side" },
      { kind: "heading", text: "Area" },
      {
        kind: "para",
        text: "Area is the amount of surface a shape covers, measured in square units. For rectangles and squares we multiply side lengths.",
      },
      { kind: "formula", text: "Area of rectangle = length × breadth    Area of square = side × side" },
      {
        kind: "example",
        problem: "A rectangle is 8 cm long and 3 cm wide. Find its area.",
        solution: "Area = length × breadth = 8 × 3 = 24 cm².",
      },
      { kind: "tip", text: "Perimeter is a length (cm, m); area is a square measure (cm², m²). Don't mix the units!" },
    ],
  },
  {
    ...C6,
    id: "6-maths-algebra",
    title: "Algebra",
    blurb: "Variables, expressions and solving simple equations.",
    ncertRef: "NCERT Class 6 Maths — Algebra",
    lesson: [
      { kind: "heading", text: "Letters for numbers" },
      {
        kind: "para",
        text: "In algebra a letter (a variable) such as x or n stands for an unknown or changing number. A fixed number is a constant.",
      },
      { kind: "heading", text: "Expressions" },
      {
        kind: "para",
        text: "Combining variables and numbers with +, −, × gives an expression, like 2n + 3. The value of an expression depends on the value of the variable.",
      },
      {
        kind: "example",
        problem: "Find the value of 2n + 3 when n = 4.",
        solution: "2 × 4 + 3 = 8 + 3 = 11.",
      },
      { kind: "heading", text: "Equations" },
      {
        kind: "para",
        text: "An equation says two expressions are equal, like x + 5 = 9. Solving it means finding the value of the variable that makes it true (here x = 4).",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-ratio-proportion",
    title: "Ratio and Proportion",
    blurb: "Comparing quantities by ratio, proportion and the unitary method.",
    ncertRef: "NCERT Class 6 Maths — Ratio and Proportion",
    lesson: [
      { kind: "heading", text: "Ratio" },
      {
        kind: "para",
        text: "A ratio compares two quantities of the same kind by division, written a : b. Like a fraction, it can be reduced to simplest form by dividing both parts by their HCF.",
      },
      {
        kind: "example",
        problem: "Write the ratio 8 : 12 in simplest form.",
        solution: "HCF of 8 and 12 is 4, so 8 : 12 = 2 : 3.",
      },
      { kind: "heading", text: "Proportion" },
      {
        kind: "para",
        text: "If two ratios are equal, the four numbers are in proportion: 2 : 3 = 8 : 12. ",
      },
      { kind: "heading", text: "Unitary method" },
      {
        kind: "para",
        text: "First find the value of one unit, then multiply for the number you need.",
      },
      {
        kind: "example",
        problem: "If 5 pens cost ₹40, what do 8 pens cost?",
        solution: "1 pen = 40 ÷ 5 = ₹8, so 8 pens = 8 × 8 = ₹64.",
      },
    ],
  },
  {
    ...C6,
    id: "6-maths-symmetry",
    title: "Symmetry",
    blurb: "Lines of symmetry and reflection in shapes and letters.",
    ncertRef: "NCERT Class 6 Maths — Symmetry",
    lesson: [
      { kind: "heading", text: "Line of symmetry" },
      {
        kind: "para",
        text: "A figure has a line of symmetry if a line can fold it into two halves that match exactly. That fold line is also called the mirror line, because each half is the reflection of the other.",
      },
      { kind: "heading", text: "How many lines?" },
      {
        kind: "list",
        items: [
          "A rectangle has 2 lines of symmetry.",
          "A square has 4.",
          "An equilateral triangle has 3.",
          "A circle has infinitely many.",
          "The letter S has none.",
        ],
      },
      { kind: "tip", text: "Test symmetry by imagining a mirror on the line — if the reflection looks identical, it's a line of symmetry." },
    ],
  },
  {
    ...C6,
    id: "6-maths-practical-geometry",
    title: "Practical Geometry (Constructions)",
    blurb: "Using ruler, compass and protractor to draw accurate figures.",
    ncertRef: "NCERT Class 6 Maths — Practical Geometry / Playing with Constructions",
    lesson: [
      { kind: "heading", text: "The tools" },
      {
        kind: "list",
        items: [
          "Ruler (straightedge): to draw and measure straight segments.",
          "Compass: to draw circles and arcs, and to copy lengths.",
          "Protractor: to measure and draw angles.",
          "Set squares: to draw perpendicular and parallel lines.",
        ],
      },
      { kind: "heading", text: "Drawing a circle" },
      {
        kind: "para",
        text: "Open the compass to the required radius, place the sharp point at the centre, and turn it once all the way around.",
      },
      { kind: "heading", text: "Copying a length" },
      {
        kind: "para",
        text: "Set the compass to the length of a segment, then mark the same opening on a new line — this copies the length without re-measuring.",
      },
      { kind: "tip", text: "Keep your pencil sharp and don't change the compass opening mid-construction — accuracy depends on it." },
    ],
  },
];

export const C6_MATH_QUESTIONS: Question[] = [
  // Knowing Our Numbers — 50 questions, easy → hard (10 gamified sets of 5)
  // --- EASY (20) ---
  { id: "q-6m-kon-1", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the place value of 5 in 352?", answer: "50", solution: "5 is in the tens place, so place value = 5 × 10 = 50." },
  { id: "q-6m-kon-2", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the face value of 7 in 718?", answer: "7", solution: "Face value is just the digit itself — 7." },
  { id: "q-6m-kon-3", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the successor of 199?", answer: "200", solution: "Successor = number + 1 = 199 + 1 = 200." },
  { id: "q-6m-kon-4", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the predecessor of 600?", answer: "599", solution: "Predecessor = number − 1 = 600 − 1 = 599." },
  { id: "q-6m-kon-5", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which number is the greatest?", options: ["234", "243", "224", "242"], answer: "243", solution: "Comparing from the left, 243 has the largest tens digit (4) among the close ones — it is greatest." },
  { id: "q-6m-kon-6", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which number is the smallest?", options: ["89", "98", "80", "79"], answer: "79", solution: "79 has the smallest tens digit (7), so it is smallest." },
  { id: "q-6m-kon-7", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "The Roman numeral for 5 is:", options: ["IV", "V", "X", "VI"], answer: "V", solution: "V stands for 5." },
  { id: "q-6m-kon-8", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "The Roman numeral X equals which number?", answer: "10", solution: "X stands for 10." },
  { id: "q-6m-kon-9", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "The number name of 45 is:", options: ["Fifty-four", "Forty-five", "Forty", "Fifteen"], answer: "Forty-five", solution: "45 is read as forty-five." },
  { id: "q-6m-kon-10", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the place value of 0 in 504?", answer: "0", solution: "The place value of 0 is always 0." },
  { id: "q-6m-kon-11", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the greatest 2-digit number?", answer: "99", solution: "The greatest 2-digit number is 99." },
  { id: "q-6m-kon-12", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the smallest 3-digit number?", answer: "100", solution: "The smallest 3-digit number is 100." },
  { id: "q-6m-kon-13", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "The Roman numeral III equals which number?", answer: "3", solution: "Three I's: 1 + 1 + 1 = 3." },
  { id: "q-6m-kon-14", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the place value of 8 in 80?", answer: "80", solution: "8 is in the tens place: 8 × 10 = 80." },
  { id: "q-6m-kon-15", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the successor of 999?", answer: "1000", solution: "999 + 1 = 1000." },
  { id: "q-6m-kon-16", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the place value of 4 in 47?", answer: "40", solution: "4 is in the tens place: 4 × 10 = 40." },
  { id: "q-6m-kon-17", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which is greater, 1000 or 999?", options: ["999", "1000", "they are equal", "cannot say"], answer: "1000", solution: "1000 has 4 digits, 999 has 3, so 1000 is greater." },
  { id: "q-6m-kon-18", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "The Roman numeral VII equals which number?", answer: "7", solution: "V + I + I = 5 + 1 + 1 = 7." },
  { id: "q-6m-kon-19", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the place value of 7 in 4,73,521?", answer: "70000", solution: "7 is in the ten-thousands place: 7 × 10,000 = 70,000." },
  { id: "q-6m-kon-20", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which number is the greatest?", options: ["9,999", "10,001", "9,990", "8,888"], answer: "10,001", solution: "10,001 has 5 digits while the others have 4, so it is greatest." },

  // --- MEDIUM (15) ---
  { id: "q-6m-kon-21", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Round 47 to the nearest 10.", answer: "50", solution: "The ones digit is 7 (≥5), so round up to 50." },
  { id: "q-6m-kon-22", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Round 432 to the nearest 100.", answer: "400", solution: "The tens digit is 3 (<5), so round down to 400." },
  { id: "q-6m-kon-23", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Round 86 to the nearest 10.", answer: "90", solution: "The ones digit is 6 (≥5), so round up to 90." },
  { id: "q-6m-kon-24", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the place value of 3 in 3,45,210?", answer: "300000", solution: "3 is in the lakhs place: 3 × 1,00,000 = 3,00,000." },
  { id: "q-6m-kon-25", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "The Roman numeral for 14 is:", options: ["XIV", "XVI", "XIIII", "VIX"], answer: "XIV", solution: "14 = 10 + 4 = X + IV = XIV." },
  { id: "q-6m-kon-26", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "The Roman numeral for 24 is:", options: ["XXIV", "XXVI", "IVXX", "XXIIII"], answer: "XXIV", solution: "24 = 20 + 4 = XX + IV = XXIV." },
  { id: "q-6m-kon-27", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "The expanded form of 502 is:", options: ["500 + 20", "500 + 2", "50 + 2", "5 + 2"], answer: "500 + 2", solution: "502 = 5 hundreds + 0 tens + 2 ones = 500 + 2." },
  { id: "q-6m-kon-28", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Form the greatest 3-digit number using the digits 4, 7 and 1 (each once).", answer: "741", solution: "Put the biggest digit first: 7, 4, 1 → 741." },
  { id: "q-6m-kon-29", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Form the smallest 3-digit number using the digits 4, 7 and 1 (each once).", answer: "147", solution: "Put the smallest digit first: 1, 4, 7 → 147." },
  { id: "q-6m-kon-30", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Round 750 to the nearest 100.", answer: "800", solution: "The tens digit is 5, so round up to 800." },
  { id: "q-6m-kon-31", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "How many thousands make 5000?", answer: "5", solution: "5000 ÷ 1000 = 5 thousands." },
  { id: "q-6m-kon-32", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Using the Indian system, 234567 is written with commas as:", options: ["234,567", "2,34,567", "23,45,67", "2,345,67"], answer: "2,34,567", solution: "Indian system groups as 2,34,567 (thousands, then lakhs)." },
  { id: "q-6m-kon-33", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "The Roman numeral XXXIX equals which number?", answer: "39", solution: "XXX = 30 and IX = 9, so 30 + 9 = 39." },
  { id: "q-6m-kon-34", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the place value of 6 in 6,00,000?", answer: "600000", solution: "6 is in the lakhs place: 6 × 1,00,000 = 6,00,000." },
  { id: "q-6m-kon-35", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the difference between the greatest and smallest 2-digit numbers?", answer: "89", solution: "99 − 10 = 89." },

  // --- HARD (15) ---
  { id: "q-6m-kon-36", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the place value of 7 in 7,23,45,678?", answer: "70000000", solution: "7 is in the crores place: 7 × 1,00,00,000 = 7,00,00,000." },
  { id: "q-6m-kon-37", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "The Roman numeral for 40 is:", options: ["XXXX", "XL", "FL", "LX"], answer: "XL", solution: "40 = 50 − 10 = XL." },
  { id: "q-6m-kon-38", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "The Roman numeral for 90 is:", options: ["IXC", "XC", "LXL", "LXXXX"], answer: "XC", solution: "90 = 100 − 10 = XC." },
  { id: "q-6m-kon-39", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "The Roman numeral for 44 is:", options: ["XLIV", "XXXXIV", "VIL", "XLVI"], answer: "XLIV", solution: "44 = 40 + 4 = XL + IV = XLIV." },
  { id: "q-6m-kon-40", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "The Roman numeral XCIX equals which number?", answer: "99", solution: "XC = 90 and IX = 9, so 90 + 9 = 99." },
  { id: "q-6m-kon-41", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Round 6,438 to the nearest 1000.", answer: "6000", solution: "The hundreds digit is 4 (<5), so round down to 6000." },
  { id: "q-6m-kon-42", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Round 6,750 to the nearest 1000.", answer: "7000", solution: "The hundreds digit is 7 (≥5), so round up to 7000." },
  { id: "q-6m-kon-43", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "In figures, how much is 1 million?", answer: "1000000", solution: "1 million = 1,000,000 (ten lakh)." },
  { id: "q-6m-kon-44", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "Which number is the greatest?", options: ["9,99,999", "10,00,000", "9,89,999", "9,90,000"], answer: "10,00,000", solution: "10,00,000 has 7 digits while the others have 6, so it is greatest." },
  { id: "q-6m-kon-45", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Form the greatest 5-digit number using the digits 8, 6, 4, 2, 0 (each once).", answer: "86420", solution: "Arrange in decreasing order: 8, 6, 4, 2, 0 → 86420." },
  { id: "q-6m-kon-46", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Form the smallest 5-digit number using the digits 8, 6, 4, 2, 0 (each once, no leading zero).", answer: "20468", solution: "Smallest non-zero digit first (2), then 0,4,6,8 → 20468." },
  { id: "q-6m-kon-47", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the place value of 5 in 4,56,78,910?", answer: "5000000", solution: "5 is in the ten-lakhs place: 5 × 10,00,000 = 50,00,000." },
  { id: "q-6m-kon-48", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "The Roman numeral for 59 is:", options: ["LIX", "LXI", "VLIX", "IL"], answer: "LIX", solution: "59 = 50 + 9 = L + IX = LIX." },
  { id: "q-6m-kon-49", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Estimate 312 + 488 by rounding each number to the nearest 100.", answer: "800", solution: "312 → 300 and 488 → 500, so the estimate is 300 + 500 = 800." },
  { id: "q-6m-kon-50", chapterId: "6-maths-knowing-our-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "How many lakhs make one crore?", answer: "100", solution: "1 crore = 100 lakh." },

  // Whole Numbers — 50 questions, easy → hard
  // --- EASY (20) ---
  { id: "q-6m-wn-1", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the successor of 4,099?", answer: "4100", solution: "Successor = number + 1 = 4,099 + 1 = 4,100." },
  { id: "q-6m-wn-2", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the predecessor of 4,100?", answer: "4099", solution: "Predecessor = number − 1 = 4,100 − 1 = 4,099." },
  { id: "q-6m-wn-3", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "The smallest whole number is:", options: ["1", "0", "−1", "there is none"], answer: "0", solution: "Whole numbers start at 0, so 0 is the smallest." },
  { id: "q-6m-wn-4", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 7 + 0?", answer: "7", solution: "Adding 0 leaves a number unchanged (0 is the additive identity)." },
  { id: "q-6m-wn-5", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 9 × 1?", answer: "9", solution: "Multiplying by 1 leaves a number unchanged (1 is the multiplicative identity)." },
  { id: "q-6m-wn-6", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 8 × 0?", answer: "0", solution: "Any number times 0 is 0." },
  { id: "q-6m-wn-7", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the successor of 0?", answer: "1", solution: "0 + 1 = 1." },
  { id: "q-6m-wn-8", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 12 + 8?", answer: "20", solution: "12 + 8 = 20." },
  { id: "q-6m-wn-9", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 15 − 6?", answer: "9", solution: "15 − 6 = 9." },
  { id: "q-6m-wn-10", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 6 × 7?", answer: "42", solution: "6 × 7 = 42." },
  { id: "q-6m-wn-11", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the predecessor of 1?", answer: "0", solution: "1 − 1 = 0." },
  { id: "q-6m-wn-12", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "The smallest natural (counting) number is:", options: ["0", "1", "2", "10"], answer: "1", solution: "Natural numbers start at 1 (whole numbers start at 0)." },
  { id: "q-6m-wn-13", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 100 + 1?", answer: "101", solution: "100 + 1 = 101." },
  { id: "q-6m-wn-14", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 9 × 10?", answer: "90", solution: "9 × 10 = 90." },
  { id: "q-6m-wn-15", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 14 − 14?", answer: "0", solution: "A number minus itself is 0." },
  { id: "q-6m-wn-16", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "The successor of a number is:", options: ["one less", "one more", "double it", "half it"], answer: "one more", solution: "The successor is one more than the number." },
  { id: "q-6m-wn-17", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 20 ÷ 4?", answer: "5", solution: "20 ÷ 4 = 5." },
  { id: "q-6m-wn-18", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Is 0 a whole number?", options: ["Yes", "No", "Only sometimes", "It is negative"], answer: "Yes", solution: "Whole numbers are 0, 1, 2, 3, … so 0 is a whole number." },
  { id: "q-6m-wn-19", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 25 + 25?", answer: "50", solution: "25 + 25 = 50." },
  { id: "q-6m-wn-20", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 8 × 5?", answer: "40", solution: "8 × 5 = 40." },

  // --- MEDIUM (15) ---
  { id: "q-6m-wn-21", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which property is shown by 4 + 5 = 5 + 4?", options: ["commutative", "associative", "distributive", "identity"], answer: "commutative", solution: "Changing the order of addition does not change the sum — commutative property." },
  { id: "q-6m-wn-22", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which property is shown by 3 × (4 + 5) = 3 × 4 + 3 × 5?", options: ["commutative", "associative", "distributive", "identity"], answer: "distributive", solution: "Multiplication distributing over addition is the distributive property." },
  { id: "q-6m-wn-23", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which property is shown by (2 + 3) + 4 = 2 + (3 + 4)?", options: ["commutative", "associative", "distributive", "identity"], answer: "associative", solution: "Regrouping the numbers does not change the sum — associative property." },
  { id: "q-6m-wn-24", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 23 × 10?", answer: "230", solution: "Multiplying by 10 adds one zero: 230." },
  { id: "q-6m-wn-25", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 45 × 100?", answer: "4500", solution: "Multiplying by 100 adds two zeros: 4500." },
  { id: "q-6m-wn-26", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Fill in the blank: 7 + ___ = 7", answer: "0", solution: "Adding 0 keeps the number the same." },
  { id: "q-6m-wn-27", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Fill in the blank: 6 × ___ = 6", answer: "1", solution: "Multiplying by 1 keeps the number the same." },
  { id: "q-6m-wn-28", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 99 + 1?", answer: "100", solution: "99 + 1 = 100." },
  { id: "q-6m-wn-29", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 1000 − 1?", answer: "999", solution: "1000 − 1 = 999." },
  { id: "q-6m-wn-30", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "The additive identity is:", options: ["0", "1", "10", "−1"], answer: "0", solution: "Adding 0 does not change a number, so 0 is the additive identity." },
  { id: "q-6m-wn-31", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "The multiplicative identity is:", options: ["0", "1", "2", "10"], answer: "1", solution: "Multiplying by 1 does not change a number, so 1 is the multiplicative identity." },
  { id: "q-6m-wn-32", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 12 × 5?", answer: "60", solution: "12 × 5 = 60." },
  { id: "q-6m-wn-33", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 144 ÷ 12?", answer: "12", solution: "144 ÷ 12 = 12." },
  { id: "q-6m-wn-34", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "Find the sum of the first 5 whole numbers (0 + 1 + 2 + 3 + 4).", answer: "10", solution: "0 + 1 + 2 + 3 + 4 = 10." },
  { id: "q-6m-wn-35", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Dividing a whole number by 0 is:", options: ["0", "1", "the number itself", "not defined"], answer: "not defined", solution: "Division by zero is not defined in mathematics." },

  // --- HARD (15) ---
  { id: "q-6m-wn-36", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Use the distributive property to find 8 × 99.", answer: "792", solution: "8 × 99 = 8 × (100 − 1) = 800 − 8 = 792." },
  { id: "q-6m-wn-37", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 25 × 16?", answer: "400", solution: "25 × 16 = 25 × 4 × 4 = 100 × 4 = 400." },
  { id: "q-6m-wn-38", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 7 × 8 × 0 × 5?", answer: "0", solution: "Any product containing 0 is 0." },
  { id: "q-6m-wn-39", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 9 × 1000?", answer: "9000", solution: "Multiplying by 1000 adds three zeros: 9000." },
  { id: "q-6m-wn-40", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 1001 − 999?", answer: "2", solution: "1001 − 999 = 2." },
  { id: "q-6m-wn-41", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 12 + 0 × 5? (Do multiplication first.)", answer: "12", solution: "0 × 5 = 0, then 12 + 0 = 12." },
  { id: "q-6m-wn-42", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 6 × (10 + 2)?", answer: "72", solution: "6 × 12 = 72 (or 6×10 + 6×2 = 60 + 12)." },
  { id: "q-6m-wn-43", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Find the sum of the first 10 whole numbers (0 to 9).", answer: "45", solution: "0 + 1 + … + 9 = 45." },
  { id: "q-6m-wn-44", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "The sum of two whole numbers is always a:", options: ["fraction", "whole number", "negative number", "decimal"], answer: "whole number", solution: "Whole numbers are closed under addition — the sum is always a whole number." },
  { id: "q-6m-wn-45", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 50 × 8?", answer: "400", solution: "50 × 8 = 400." },
  { id: "q-6m-wn-46", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the predecessor of 10,000?", answer: "9999", solution: "10,000 − 1 = 9,999." },
  { id: "q-6m-wn-47", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 35 × 11?", answer: "385", solution: "35 × 11 = 35 × 10 + 35 = 350 + 35 = 385." },
  { id: "q-6m-wn-48", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 1000 ÷ 100?", answer: "10", solution: "1000 ÷ 100 = 10." },
  { id: "q-6m-wn-49", chapterId: "6-maths-whole-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "Use the distributive property: 9 × 6 + 9 × 4 = ?", answer: "90", solution: "9 × 6 + 9 × 4 = 9 × (6 + 4) = 9 × 10 = 90." },
  { id: "q-6m-wn-50", chapterId: "6-maths-whole-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "Which whole number has no predecessor (within whole numbers)?", options: ["0", "1", "10", "100"], answer: "0", solution: "0 is the smallest whole number, so it has no whole-number predecessor." },

  // Patterns
  {
    id: "q-6m-pat-1",
    chapterId: "6-maths-patterns",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "Find the next number: 2, 5, 8, 11, ?",
    answer: "14",
    solution: "Each term increases by 3, so 11 + 3 = 14.",
  },
  {
    id: "q-6m-pat-2",
    chapterId: "6-maths-patterns",
    ...C6,
    type: "mcq",
    difficulty: "medium",
    prompt: "Which list shows the square numbers?",
    options: ["1, 3, 6, 10", "1, 4, 9, 16", "2, 4, 6, 8", "1, 2, 4, 8"],
    answer: "1, 4, 9, 16",
    solution: "Square numbers are n × n: 1, 4, 9, 16, 25 …",
  },

  // Number Play
  {
    id: "q-6m-np-1",
    chapterId: "6-maths-number-play",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "Which of these is a palindrome?",
    options: ["123", "454", "210", "678"],
    answer: "454",
    solution: "454 reads the same forwards and backwards.",
  },
  {
    id: "q-6m-np-2",
    chapterId: "6-maths-number-play",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "What is the digit sum of 142?",
    answer: "7",
    solution: "1 + 4 + 2 = 7.",
  },

  // Playing with Numbers / Prime Time — 50 questions, easy → hard
  // --- EASY (20) ---
  { id: "q-6m-pwn-1", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which number is prime?", options: ["9", "15", "17", "21"], answer: "17", solution: "17 has only two factors, 1 and 17." },
  { id: "q-6m-pwn-2", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the smallest prime number?", answer: "2", solution: "2 is the smallest (and only even) prime." },
  { id: "q-6m-pwn-3", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Is 8 even or odd?", options: ["Even", "Odd", "Both", "Neither"], answer: "Even", solution: "8 is divisible by 2, so it is even." },
  { id: "q-6m-pwn-4", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "How many factors does 1 have?", answer: "1", solution: "1 has only one factor — itself." },
  { id: "q-6m-pwn-5", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which number is composite?", options: ["2", "3", "5", "9"], answer: "9", solution: "9 = 3 × 3 has more than two factors, so it is composite." },
  { id: "q-6m-pwn-6", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the 3rd multiple of 5?", answer: "15", solution: "5 × 3 = 15." },
  { id: "q-6m-pwn-7", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which of these is even?", options: ["7", "9", "12", "15"], answer: "12", solution: "12 is divisible by 2." },
  { id: "q-6m-pwn-8", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the smallest factor of any number?", answer: "1", solution: "1 divides every number, so it is the smallest factor." },
  { id: "q-6m-pwn-9", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the largest factor of 12?", answer: "12", solution: "The largest factor of any number is the number itself." },
  { id: "q-6m-pwn-10", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Is 1 a prime number?", options: ["Yes", "No, it is neither prime nor composite", "It is composite", "Sometimes"], answer: "No, it is neither prime nor composite", solution: "1 has only one factor, so it is neither prime nor composite." },
  { id: "q-6m-pwn-11", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the next multiple of 4 after 12?", answer: "16", solution: "12 + 4 = 16." },
  { id: "q-6m-pwn-12", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which of these is odd?", options: ["10", "14", "21", "8"], answer: "21", solution: "21 is not divisible by 2, so it is odd." },
  { id: "q-6m-pwn-13", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "How many factors does 7 have?", answer: "2", solution: "7 is prime, so it has exactly two factors: 1 and 7." },
  { id: "q-6m-pwn-14", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the 2nd multiple of 9?", answer: "18", solution: "9 × 2 = 18." },
  { id: "q-6m-pwn-15", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "The only even prime number is:", options: ["1", "2", "4", "9"], answer: "2", solution: "2 is the only even number that is prime." },
  { id: "q-6m-pwn-16", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Is 15 divisible by 5?", options: ["Yes", "No", "Only by 2", "Never"], answer: "Yes", solution: "15 ends in 5, so it is divisible by 5 (15 ÷ 5 = 3)." },
  { id: "q-6m-pwn-17", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "How many factors does 6 have? (1, 2, 3, 6)", answer: "4", solution: "The factors of 6 are 1, 2, 3 and 6 — four factors." },
  { id: "q-6m-pwn-18", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the 5th multiple of 2?", answer: "10", solution: "2 × 5 = 10." },
  { id: "q-6m-pwn-19", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "easy", prompt: "Which number is a multiple of 10?", options: ["25", "40", "33", "17"], answer: "40", solution: "40 ends in 0, so it is a multiple of 10." },
  { id: "q-6m-pwn-20", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "easy", prompt: "What is the smallest composite number?", answer: "4", solution: "4 is the smallest number with more than two factors (1, 2, 4)." },

  // --- MEDIUM (15) ---
  { id: "q-6m-pwn-21", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which number is divisible by 2?", options: ["31", "44", "57", "69"], answer: "44", solution: "44 is even (ends in 4), so it is divisible by 2." },
  { id: "q-6m-pwn-22", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which number is divisible by 5?", options: ["52", "75", "38", "91"], answer: "75", solution: "75 ends in 5, so it is divisible by 5." },
  { id: "q-6m-pwn-23", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which number is divisible by 10?", options: ["45", "120", "57", "99"], answer: "120", solution: "120 ends in 0, so it is divisible by 10." },
  { id: "q-6m-pwn-24", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which number is divisible by 3?", options: ["124", "238", "234", "100"], answer: "234", solution: "Digit sum of 234 = 9, divisible by 3." },
  { id: "q-6m-pwn-25", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the HCF of 12 and 18?", answer: "6", solution: "12 = 2×2×3, 18 = 2×3×3; common factors 2×3 = 6." },
  { id: "q-6m-pwn-26", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the HCF of 8 and 12?", answer: "4", solution: "8 = 2×2×2, 12 = 2×2×3; common 2×2 = 4." },
  { id: "q-6m-pwn-27", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the LCM of 4 and 6?", answer: "12", solution: "Multiples of 4: 4,8,12; of 6: 6,12. Smallest common = 12." },
  { id: "q-6m-pwn-28", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the LCM of 3 and 5?", answer: "15", solution: "3 and 5 share no factors, so LCM = 3 × 5 = 15." },
  { id: "q-6m-pwn-29", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What number has the prime factorization 2 × 2 × 3?", answer: "12", solution: "2 × 2 × 3 = 12." },
  { id: "q-6m-pwn-30", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "How many prime numbers are there between 1 and 10?", answer: "4", solution: "They are 2, 3, 5 and 7 — four primes." },
  { id: "q-6m-pwn-31", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Which number is divisible by 9?", options: ["234", "189", "400", "123"], answer: "189", solution: "Digit sum of 189 = 18, divisible by 9." },
  { id: "q-6m-pwn-32", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the HCF of 9 and 6?", answer: "3", solution: "Common factor of 9 (1,3,9) and 6 (1,2,3,6) is 3." },
  { id: "q-6m-pwn-33", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "What is the LCM of 6 and 8?", answer: "24", solution: "6 = 2×3, 8 = 2×2×2; LCM = 2×2×2×3 = 24." },
  { id: "q-6m-pwn-34", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "medium", prompt: "How many factors does 16 have? (1, 2, 4, 8, 16)", answer: "5", solution: "16 has five factors: 1, 2, 4, 8, 16." },
  { id: "q-6m-pwn-35", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "medium", prompt: "Two numbers whose HCF is 1 are called:", options: ["twin", "co-prime", "perfect", "composite"], answer: "co-prime", solution: "Numbers with HCF 1 share no common factor other than 1 — co-prime." },

  // --- HARD (15) ---
  { id: "q-6m-pwn-36", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the HCF of 24 and 36?", answer: "12", solution: "24 = 2³×3, 36 = 2²×3²; common = 2²×3 = 12." },
  { id: "q-6m-pwn-37", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the LCM of 12 and 18?", answer: "36", solution: "12 = 2²×3, 18 = 2×3²; LCM = 2²×3² = 36." },
  { id: "q-6m-pwn-38", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What number has the prime factorization 2 × 2 × 3 × 3?", answer: "36", solution: "2 × 2 × 3 × 3 = 36." },
  { id: "q-6m-pwn-39", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the HCF of 16 and 24?", answer: "8", solution: "16 = 2⁴, 24 = 2³×3; common = 2³ = 8." },
  { id: "q-6m-pwn-40", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the LCM of 8 and 12?", answer: "24", solution: "8 = 2³, 12 = 2²×3; LCM = 2³×3 = 24." },
  { id: "q-6m-pwn-41", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the LCM of 5 and 7?", answer: "35", solution: "5 and 7 are co-prime, so LCM = 5 × 7 = 35." },
  { id: "q-6m-pwn-42", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "For 4 and 6, what is HCF × LCM?", answer: "24", solution: "HCF(4,6)=2, LCM=12; 2 × 12 = 24, which also equals 4 × 6." },
  { id: "q-6m-pwn-43", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the smallest number divisible by both 2 and 3?", answer: "6", solution: "The LCM of 2 and 3 is 6." },
  { id: "q-6m-pwn-44", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "Which pair of numbers is co-prime?", options: ["(8, 12)", "(9, 16)", "(6, 9)", "(10, 15)"], answer: "(9, 16)", solution: "9 and 16 share no common factor except 1, so HCF = 1 — co-prime." },
  { id: "q-6m-pwn-45", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "How many factors does 24 have?", answer: "8", solution: "1, 2, 3, 4, 6, 8, 12, 24 — eight factors." },
  { id: "q-6m-pwn-46", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the HCF of 18 and 24?", answer: "6", solution: "18 = 2×3², 24 = 2³×3; common = 2×3 = 6." },
  { id: "q-6m-pwn-47", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the LCM of 9 and 12?", answer: "36", solution: "9 = 3², 12 = 2²×3; LCM = 2²×3² = 36." },
  { id: "q-6m-pwn-48", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the largest 2-digit prime number?", answer: "97", solution: "97 has no factors other than 1 and itself, and is the largest prime below 100." },
  { id: "q-6m-pwn-49", chapterId: "6-maths-playing-with-numbers", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the sum of the first three prime numbers?", answer: "10", solution: "2 + 3 + 5 = 10." },
  { id: "q-6m-pwn-50", chapterId: "6-maths-playing-with-numbers", ...C6, type: "mcq", difficulty: "hard", prompt: "A 'perfect number' equals the sum of its factors (excluding itself). Which is perfect?", options: ["4", "6", "8", "9"], answer: "6", solution: "Factors of 6 (excluding 6) are 1, 2, 3 and 1 + 2 + 3 = 6." },

  // Basic Geometrical Ideas
  {
    id: "q-6m-bgi-1",
    chapterId: "6-maths-basic-geometrical-ideas",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "A part of a line with two endpoints is called a:",
    options: ["ray", "line segment", "point", "plane"],
    answer: "line segment",
    solution: "A line segment has two endpoints; a ray has one and a line has none.",
  },
  {
    id: "q-6m-bgi-2",
    chapterId: "6-maths-basic-geometrical-ideas",
    ...C6,
    type: "mcq",
    difficulty: "medium",
    prompt: "The longest chord of a circle is the:",
    options: ["radius", "arc", "diameter", "tangent"],
    answer: "diameter",
    solution: "The diameter passes through the centre and is the longest chord (= 2 × radius).",
  },

  // Lines and Angles
  {
    id: "q-6m-la-1",
    chapterId: "6-maths-lines-and-angles",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "An angle of 120° is:",
    options: ["acute", "right", "obtuse", "straight"],
    answer: "obtuse",
    solution: "Between 90° and 180° is obtuse.",
  },
  {
    id: "q-6m-la-2",
    chapterId: "6-maths-lines-and-angles",
    ...C6,
    type: "numeric",
    difficulty: "medium",
    prompt: "What is the supplement of 110° (in degrees)?",
    answer: "70",
    solution: "Supplementary angles add to 180°, so 180 − 110 = 70.",
  },

  // Understanding Elementary Shapes
  {
    id: "q-6m-es-1",
    chapterId: "6-maths-elementary-shapes",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "How many edges does a cube have?",
    answer: "12",
    solution: "A cube has 6 faces, 12 edges and 8 vertices.",
  },
  {
    id: "q-6m-es-2",
    chapterId: "6-maths-elementary-shapes",
    ...C6,
    type: "mcq",
    difficulty: "medium",
    prompt: "A triangle with all three sides equal is called:",
    options: ["scalene", "isosceles", "equilateral", "right"],
    answer: "equilateral",
    solution: "Equilateral means all sides (and angles) are equal.",
  },

  // Fractions — 50 questions, easy → hard
  // --- EASY (20) ---
  { id: "q-6m-fr-1", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "Which fraction is equivalent to 1/2?", options: ["2/3", "3/6", "2/5", "4/6"], answer: "3/6", solution: "Multiply top and bottom of 1/2 by 3: 3/6." },
  { id: "q-6m-fr-2", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "7/4 is an example of a/an:", options: ["proper fraction", "improper fraction", "mixed number", "whole number"], answer: "improper fraction", solution: "Numerator (7) > denominator (4), so it is improper." },
  { id: "q-6m-fr-3", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "Add 1/5 + 3/5. The answer is _/5 — give the numerator.", answer: "4", solution: "Same denominator: (1 + 3)/5 = 4/5." },
  { id: "q-6m-fr-4", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "In the fraction 3/4, the denominator is:", options: ["3", "4", "7", "1"], answer: "4", solution: "The denominator is the bottom number — 4." },
  { id: "q-6m-fr-5", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "In the fraction 3/4, the numerator is:", options: ["3", "4", "7", "12"], answer: "3", solution: "The numerator is the top number — 3." },
  { id: "q-6m-fr-6", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 1/2 of 10?", answer: "5", solution: "10 ÷ 2 = 5." },
  { id: "q-6m-fr-7", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 1/3 of 9?", answer: "3", solution: "9 ÷ 3 = 3." },
  { id: "q-6m-fr-8", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "Which of these is a proper fraction?", options: ["5/3", "7/7", "2/5", "9/4"], answer: "2/5", solution: "A proper fraction has numerator < denominator: 2/5." },
  { id: "q-6m-fr-9", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "Which fraction is equivalent to 1/3?", options: ["2/3", "2/6", "3/4", "1/6"], answer: "2/6", solution: "Multiply top and bottom of 1/3 by 2: 2/6." },
  { id: "q-6m-fr-10", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "Add 2/7 + 3/7. The answer is _/7 — give the numerator.", answer: "5", solution: "(2 + 3)/7 = 5/7." },
  { id: "q-6m-fr-11", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "Which fraction equals 1 whole?", options: ["3/4", "5/5", "2/3", "7/8"], answer: "5/5", solution: "When numerator = denominator, the fraction equals 1." },
  { id: "q-6m-fr-12", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 1/4 of 8?", answer: "2", solution: "8 ÷ 4 = 2." },
  { id: "q-6m-fr-13", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "The simplest form of 2/4 is:", options: ["1/2", "2/4", "1/4", "4/2"], answer: "1/2", solution: "Divide top and bottom by 2: 1/2." },
  { id: "q-6m-fr-14", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "Which is bigger, 1/2 or 1/4?", options: ["1/2", "1/4", "they are equal", "cannot tell"], answer: "1/2", solution: "With the same numerator, the smaller denominator is the bigger fraction." },
  { id: "q-6m-fr-15", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "Subtract 5/8 − 2/8. The answer is _/8 — give the numerator.", answer: "3", solution: "(5 − 2)/8 = 3/8." },
  { id: "q-6m-fr-16", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "1/2 written with denominator 8 is:", options: ["2/8", "4/8", "8/8", "1/8"], answer: "4/8", solution: "Multiply top and bottom of 1/2 by 4: 4/8." },
  { id: "q-6m-fr-17", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 1/5 of 20?", answer: "4", solution: "20 ÷ 5 = 4." },
  { id: "q-6m-fr-18", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "Which is a unit fraction?", options: ["2/3", "1/7", "5/8", "3/4"], answer: "1/7", solution: "A unit fraction has numerator 1." },
  { id: "q-6m-fr-19", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "easy", prompt: "How is 'two and a half' written as a mixed number?", options: ["2/2", "5/2", "2½", "½"], answer: "2½", solution: "Two wholes and a half = 2½." },
  { id: "q-6m-fr-20", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "easy", prompt: "What is 1/2 of 6?", answer: "3", solution: "6 ÷ 2 = 3." },

  // --- MEDIUM (15) ---
  { id: "q-6m-fr-21", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "The simplest form of 6/9 is:", options: ["2/3", "3/4", "6/9", "1/3"], answer: "2/3", solution: "Divide top and bottom by 3: 2/3." },
  { id: "q-6m-fr-22", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "Which fraction is equivalent to 3/4?", options: ["6/8", "4/6", "9/16", "2/3"], answer: "6/8", solution: "Multiply top and bottom of 3/4 by 2: 6/8." },
  { id: "q-6m-fr-23", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "medium", prompt: "Add 3/10 + 4/10. The answer is _/10 — give the numerator.", answer: "7", solution: "(3 + 4)/10 = 7/10." },
  { id: "q-6m-fr-24", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "Which is bigger, 2/3 or 3/4?", options: ["2/3", "3/4", "they are equal", "cannot say"], answer: "3/4", solution: "2/3 = 8/12 and 3/4 = 9/12, so 3/4 is bigger." },
  { id: "q-6m-fr-25", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 2/3 of 12?", answer: "8", solution: "12 ÷ 3 = 4, then 4 × 2 = 8." },
  { id: "q-6m-fr-26", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "Write 1¾ as an improper fraction.", options: ["7/4", "4/7", "3/4", "11/4"], answer: "7/4", solution: "1¾ = (1×4 + 3)/4 = 7/4." },
  { id: "q-6m-fr-27", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "Write 9/4 as a mixed number.", options: ["2¼", "4½", "2½", "9/4"], answer: "2¼", solution: "9 ÷ 4 = 2 remainder 1 → 2¼." },
  { id: "q-6m-fr-28", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "medium", prompt: "Subtract 7/12 − 1/12. The answer is _/12 — give the numerator.", answer: "6", solution: "(7 − 1)/12 = 6/12." },
  { id: "q-6m-fr-29", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "The simplest form of 10/15 is:", options: ["2/3", "3/5", "5/10", "10/15"], answer: "2/3", solution: "Divide top and bottom by 5: 2/3." },
  { id: "q-6m-fr-30", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 3/4 of 16?", answer: "12", solution: "16 ÷ 4 = 4, then 4 × 3 = 12." },
  { id: "q-6m-fr-31", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "Which fraction is the largest?", options: ["1/2", "3/8", "5/8", "1/4"], answer: "5/8", solution: "As eighths: 4/8, 3/8, 5/8, 2/8 — the largest is 5/8." },
  { id: "q-6m-fr-32", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 1/2 + 1/2? (Give the whole number.)", answer: "1", solution: "1/2 + 1/2 = 2/2 = 1." },
  { id: "q-6m-fr-33", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "Which fraction is equivalent to 2/5?", options: ["4/10", "5/2", "2/10", "6/10"], answer: "4/10", solution: "Multiply top and bottom of 2/5 by 2: 4/10." },
  { id: "q-6m-fr-34", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "medium", prompt: "What is 5/6 of 12?", answer: "10", solution: "12 ÷ 6 = 2, then 2 × 5 = 10." },
  { id: "q-6m-fr-35", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "medium", prompt: "The simplest form of 8/12 is:", options: ["2/3", "4/6", "3/4", "8/12"], answer: "2/3", solution: "Divide top and bottom by 4: 2/3." },

  // --- HARD (15) ---
  { id: "q-6m-fr-36", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "Add 1/2 + 1/4. The answer is _/4 — give the numerator.", answer: "3", solution: "1/2 = 2/4, so 2/4 + 1/4 = 3/4." },
  { id: "q-6m-fr-37", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "What is 1/2 + 1/3?", options: ["2/5", "5/6", "1/6", "3/5"], answer: "5/6", solution: "Common denominator 6: 3/6 + 2/6 = 5/6." },
  { id: "q-6m-fr-38", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "Subtract 3/4 − 1/2. The answer is _/4 — give the numerator.", answer: "1", solution: "1/2 = 2/4, so 3/4 − 2/4 = 1/4." },
  { id: "q-6m-fr-39", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "Which fraction is already in its simplest form?", options: ["4/8", "6/9", "5/7", "10/20"], answer: "5/7", solution: "5 and 7 share no common factor other than 1." },
  { id: "q-6m-fr-40", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 7/8 of 16?", answer: "14", solution: "16 ÷ 8 = 2, then 2 × 7 = 14." },
  { id: "q-6m-fr-41", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "What is 2/3 + 1/6?", options: ["3/9", "5/6", "1/2", "3/6"], answer: "5/6", solution: "2/3 = 4/6, so 4/6 + 1/6 = 5/6." },
  { id: "q-6m-fr-42", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "What is the lowest common denominator of 1/4 and 1/6?", answer: "12", solution: "The LCM of 4 and 6 is 12." },
  { id: "q-6m-fr-43", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "What is 5/6 − 1/3?", options: ["1/2", "4/3", "1/6", "2/3"], answer: "1/2", solution: "1/3 = 2/6, so 5/6 − 2/6 = 3/6 = 1/2." },
  { id: "q-6m-fr-44", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 2/5 of 35?", answer: "14", solution: "35 ÷ 5 = 7, then 7 × 2 = 14." },
  { id: "q-6m-fr-45", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "Which fraction is the smallest?", options: ["1/2", "2/3", "1/6", "3/4"], answer: "1/6", solution: "As twelfths: 6/12, 8/12, 2/12, 9/12 — the smallest is 1/6." },
  { id: "q-6m-fr-46", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "Write 11/4 as a mixed number. What is the whole-number part?", answer: "2", solution: "11 ÷ 4 = 2 remainder 3 → 2¾, whole part 2." },
  { id: "q-6m-fr-47", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "What is 3/8 + 3/8 in simplest form?", options: ["6/16", "3/4", "6/8 only", "9/8"], answer: "3/4", solution: "3/8 + 3/8 = 6/8 = 3/4." },
  { id: "q-6m-fr-48", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 1/2 + 1/4 + 1/4? (Give the whole number.)", answer: "1", solution: "2/4 + 1/4 + 1/4 = 4/4 = 1." },
  { id: "q-6m-fr-49", chapterId: "6-maths-fractions", ...C6, type: "mcq", difficulty: "hard", prompt: "What is 1 − 3/5?", options: ["2/5", "3/5", "1/5", "4/5"], answer: "2/5", solution: "1 = 5/5, so 5/5 − 3/5 = 2/5." },
  { id: "q-6m-fr-50", chapterId: "6-maths-fractions", ...C6, type: "numeric", difficulty: "hard", prompt: "What is 4/5 of 25?", answer: "20", solution: "25 ÷ 5 = 5, then 5 × 4 = 20." },

  // Decimals
  {
    id: "q-6m-dec-1",
    chapterId: "6-maths-decimals",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "Write 3/4 as a decimal.",
    options: ["0.34", "0.75", "0.43", "0.50"],
    answer: "0.75",
    solution: "3/4 = 75/100 = 0.75.",
  },
  {
    id: "q-6m-dec-2",
    chapterId: "6-maths-decimals",
    ...C6,
    type: "numeric",
    difficulty: "medium",
    prompt: "Add 2.5 + 1.75",
    answer: "4.25",
    solution: "Line up the points: 2.50 + 1.75 = 4.25.",
  },

  // Data Handling
  {
    id: "q-6m-dh-1",
    chapterId: "6-maths-data-handling",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "In a pictograph, ⭐ = 10 books. How many books do 4 stars represent?",
    answer: "40",
    solution: "4 × 10 = 40 books.",
  },
  {
    id: "q-6m-dh-2",
    chapterId: "6-maths-data-handling",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "How many items does one group of tally marks (||||̸ ) represent?",
    answer: "5",
    solution: "A crossed group of tally marks stands for 5.",
  },

  // Mensuration
  {
    id: "q-6m-men-1",
    chapterId: "6-maths-mensuration",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "Find the area of a rectangle 8 cm long and 3 cm wide (in cm²).",
    answer: "24",
    solution: "Area = length × breadth = 8 × 3 = 24 cm².",
  },
  {
    id: "q-6m-men-2",
    chapterId: "6-maths-mensuration",
    ...C6,
    type: "numeric",
    difficulty: "medium",
    prompt: "Find the perimeter of a square of side 6 cm (in cm).",
    answer: "24",
    solution: "Perimeter of a square = 4 × side = 4 × 6 = 24 cm.",
  },

  // Algebra
  {
    id: "q-6m-alg-1",
    chapterId: "6-maths-algebra",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "Find the value of 2n + 3 when n = 4.",
    answer: "11",
    solution: "2 × 4 + 3 = 8 + 3 = 11.",
  },
  {
    id: "q-6m-alg-2",
    chapterId: "6-maths-algebra",
    ...C6,
    type: "numeric",
    difficulty: "medium",
    prompt: "Solve for x: x + 5 = 9.",
    answer: "4",
    solution: "Subtract 5 from both sides: x = 9 − 5 = 4.",
  },

  // Ratio and Proportion
  {
    id: "q-6m-rp-1",
    chapterId: "6-maths-ratio-proportion",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "Write 8 : 12 in simplest form.",
    options: ["2 : 3", "4 : 5", "1 : 2", "3 : 4"],
    answer: "2 : 3",
    solution: "Divide both by their HCF 4: 8 : 12 = 2 : 3.",
  },
  {
    id: "q-6m-rp-2",
    chapterId: "6-maths-ratio-proportion",
    ...C6,
    type: "numeric",
    difficulty: "medium",
    prompt: "If 5 pens cost ₹40, what do 8 pens cost (in ₹)?",
    answer: "64",
    solution: "1 pen = 40 ÷ 5 = ₹8; 8 pens = 8 × 8 = ₹64.",
  },

  // Symmetry
  {
    id: "q-6m-sym-1",
    chapterId: "6-maths-symmetry",
    ...C6,
    type: "numeric",
    difficulty: "easy",
    prompt: "How many lines of symmetry does a square have?",
    answer: "4",
    solution: "A square has 4 lines of symmetry (2 diagonals + 2 through opposite side-midpoints).",
  },
  {
    id: "q-6m-sym-2",
    chapterId: "6-maths-symmetry",
    ...C6,
    type: "mcq",
    difficulty: "medium",
    prompt: "Which letter has NO line of symmetry?",
    options: ["A", "H", "S", "M"],
    answer: "S",
    solution: "S cannot be folded into two matching halves, so it has no line of symmetry.",
  },

  // Practical Geometry
  {
    id: "q-6m-pg-1",
    chapterId: "6-maths-practical-geometry",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "Which instrument is used to draw a circle?",
    options: ["ruler", "compass", "protractor", "set square"],
    answer: "compass",
    solution: "A compass draws circles and arcs of a chosen radius.",
  },
  {
    id: "q-6m-pg-2",
    chapterId: "6-maths-practical-geometry",
    ...C6,
    type: "mcq",
    difficulty: "easy",
    prompt: "Which instrument is used to measure an angle?",
    options: ["ruler", "compass", "protractor", "divider"],
    answer: "protractor",
    solution: "A protractor measures angles in degrees.",
  },
];
