import type { Chapter, Question } from "./types";

// ---------------------------------------------------------------------------
// CLASS 6 SCIENCE — Physics, Chemistry, Biology chapters with lessons.
// Maps NCERT "Curiosity" (2025–26) + classic NCERT Class 6 Science topics into
// the app's three science subjects. The Motion and Measurement chapter lives in
// seed.ts; everything else is here. Spread into CHAPTERS / QUESTIONS by seed.ts.
// ---------------------------------------------------------------------------

export const C6_SCIENCE_CHAPTERS: Chapter[] = [
  // ===================== PHYSICS =====================
  {
    id: "6-physics-magnets",
    classId: "6",
    subjectId: "physics",
    title: "Exploring Magnets",
    blurb: "Magnetic materials, poles, attraction and repulsion, and the compass.",
    ncertRef: "NCERT Class 6 Science — Exploring Magnets / Fun with Magnets",
    lesson: [
      { kind: "heading", text: "What magnets attract" },
      {
        kind: "para",
        text: "A magnet pulls certain materials towards it. Materials that are attracted — iron, nickel and cobalt — are called magnetic materials. Things like wood, plastic, paper and rubber are non-magnetic.",
      },
      { kind: "heading", text: "Poles of a magnet" },
      {
        kind: "para",
        text: "Every magnet has two poles — a north pole (N) and a south pole (S). The pulling force is strongest at the poles. No matter how many times you break a magnet, each piece still has both poles.",
      },
      { kind: "heading", text: "Attraction and repulsion" },
      {
        kind: "list",
        items: [
          "Like poles (N–N or S–S) repel each other.",
          "Unlike poles (N–S) attract each other.",
        ],
      },
      {
        kind: "para",
        text: "A freely hanging magnet always comes to rest pointing north–south. This is how a compass works to find direction.",
      },
      { kind: "tip", text: "Keep magnets away from mobile phones, cards and watches — they can damage them." },
    ],
  },
  {
    id: "6-physics-temperature",
    classId: "6",
    subjectId: "physics",
    title: "Temperature and its Measurement",
    blurb: "Hotness and coldness, thermometers, and the Celsius scale.",
    ncertRef: "NCERT Class 6 Science — Temperature and its Measurement",
    lesson: [
      { kind: "heading", text: "What is temperature?" },
      {
        kind: "para",
        text: "Temperature is a measure of how hot or cold something is. Our sense of touch is unreliable for this, so we use a thermometer, which measures temperature in degrees Celsius (°C).",
      },
      { kind: "heading", text: "Two kinds of thermometer" },
      {
        kind: "list",
        items: [
          "Clinical thermometer: measures body temperature, range about 35°C to 42°C.",
          "Laboratory thermometer: a wider range, for experiments and surroundings.",
        ],
      },
      {
        kind: "para",
        text: "The normal temperature of a healthy human body is about 37°C.",
      },
      { kind: "tip", text: "Read a thermometer with your eye level with the top of the liquid thread for an accurate value." },
    ],
  },
  {
    id: "6-physics-light-shadows",
    classId: "6",
    subjectId: "physics",
    title: "Light, Shadows and Reflections",
    blurb: "Luminous objects, transparency, how shadows form, and reflection.",
    ncertRef: "NCERT Class 6 Science — Light, Shadows and Reflections",
    lesson: [
      { kind: "heading", text: "Sources of light" },
      {
        kind: "para",
        text: "Objects that give out their own light (the Sun, a flame, a bulb) are luminous. Objects that only reflect light from others (the Moon, a book) are non-luminous.",
      },
      { kind: "heading", text: "How materials treat light" },
      {
        kind: "list",
        items: [
          "Transparent: light passes through fully (clear glass, water).",
          "Translucent: light passes partly (butter paper, frosted glass).",
          "Opaque: no light passes through (wood, a metal sheet).",
        ],
      },
      { kind: "heading", text: "Shadows" },
      {
        kind: "para",
        text: "Light travels in a straight line. When an opaque object blocks it, a dark shadow forms on a screen behind. A shadow shows only the outline (shape) of the object and is always black, whatever the object's colour.",
      },
      { kind: "tip", text: "You need three things for a shadow: a source of light, an opaque object, and a screen." },
    ],
  },
  {
    id: "6-physics-electricity",
    classId: "6",
    subjectId: "physics",
    title: "Electricity and Circuits",
    blurb: "Cells, bulbs, circuits, switches, and conductors vs insulators.",
    ncertRef: "NCERT Class 6 Science — Electricity and Circuits",
    lesson: [
      { kind: "heading", text: "Electric circuits" },
      {
        kind: "para",
        text: "An electric cell stores electricity and has two terminals — positive (+) and negative (−). A bulb lights up only when it is part of a complete (closed) circuit, where electricity can flow all the way from one terminal back to the other.",
      },
      { kind: "heading", text: "Switches" },
      {
        kind: "para",
        text: "A switch opens or closes a circuit. Closed (ON) → the bulb glows. Open (OFF) → the path is broken and the bulb stays off.",
      },
      { kind: "heading", text: "Conductors and insulators" },
      {
        kind: "list",
        items: [
          "Conductors let electricity pass through them (metals like copper and iron).",
          "Insulators do not (plastic, rubber, wood) — that's why wires are coated in plastic.",
        ],
      },
      { kind: "tip", text: "Never experiment with the electricity from wall sockets — it is dangerous. Use only cells/batteries." },
    ],
  },
  {
    id: "6-physics-beyond-earth",
    classId: "6",
    subjectId: "physics",
    title: "Beyond Earth",
    blurb: "The Sun, the planets of the solar system, stars and the Moon.",
    ncertRef: "NCERT Class 6 Science — Beyond Earth",
    lesson: [
      { kind: "heading", text: "Our solar system" },
      {
        kind: "para",
        text: "The Sun is a star — a huge ball of hot, glowing gas — at the centre of our solar system. Eight planets move around it in fixed paths called orbits.",
      },
      {
        kind: "list",
        items: [
          "In order from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
          "Mercury is closest to the Sun; Jupiter is the largest planet.",
          "The Moon is Earth's natural satellite — it has no light of its own and reflects sunlight.",
        ],
      },
      { kind: "tip", text: "Stars look tiny only because they are extremely far away — many are far bigger than the Sun." },
    ],
  },

  // ===================== CHEMISTRY =====================
  {
    id: "6-chemistry-materials",
    classId: "6",
    subjectId: "chemistry",
    title: "Materials Around Us",
    blurb: "Objects and materials, their properties, and grouping them.",
    ncertRef: "NCERT Class 6 Science — Materials Around Us / Sorting Materials",
    lesson: [
      { kind: "heading", text: "Objects and materials" },
      {
        kind: "para",
        text: "Every object is made of one or more materials. The same object can be made from different materials (a chair of wood, plastic or metal), and one material can make many objects.",
      },
      { kind: "heading", text: "Properties of materials" },
      {
        kind: "list",
        items: [
          "Appearance: shiny (lustrous) or dull.",
          "Hardness: hard (iron) or soft (sponge).",
          "Solubility: soluble (sugar, salt dissolve in water) or insoluble (sand, chalk).",
          "Float or sink in water; transparent, translucent or opaque.",
        ],
      },
      {
        kind: "para",
        text: "We group materials by shared properties to study and use them better.",
      },
      {
        kind: "example",
        problem: "Does sugar dissolve in water?",
        solution: "Yes — sugar is soluble in water, so it disappears into the water forming a solution.",
      },
    ],
  },
  {
    id: "6-chemistry-separation",
    classId: "6",
    subjectId: "chemistry",
    title: "Methods of Separation",
    blurb: "Handpicking, sieving, filtration, evaporation and more.",
    ncertRef: "NCERT Class 6 Science — Methods of Separation in Everyday Life",
    lesson: [
      { kind: "heading", text: "Why separate?" },
      {
        kind: "para",
        text: "We separate the useful part of a mixture from the unwanted part, or separate two useful things. The method we pick depends on the properties of the things being separated.",
      },
      { kind: "heading", text: "Common methods" },
      {
        kind: "list",
        items: [
          "Handpicking: remove a few visible bits (stones from rice).",
          "Winnowing: wind blows away lighter husk from heavier grain.",
          "Sieving: small particles fall through; larger stay (flour from bran).",
          "Sedimentation & decantation: let heavier solids settle, then pour off the liquid.",
          "Filtration: pass through a filter to remove insoluble solids (sand from water).",
          "Evaporation: heat a solution so water leaves and the dissolved solid stays (salt from sea water).",
        ],
      },
      {
        kind: "example",
        problem: "How would you separate sand mixed in water?",
        solution: "By filtration — sand is insoluble, so it stays on the filter while clear water passes through.",
      },
    ],
  },
  {
    id: "6-chemistry-states-of-water",
    classId: "6",
    subjectId: "chemistry",
    title: "A Journey through States of Water",
    blurb: "Solid, liquid and gas; evaporation, condensation and the water cycle.",
    ncertRef: "NCERT Class 6 Science — A Journey through States of Water",
    lesson: [
      { kind: "heading", text: "Three states of water" },
      {
        kind: "list",
        items: [
          "Solid — ice.",
          "Liquid — water.",
          "Gas — water vapour (steam).",
        ],
      },
      { kind: "heading", text: "Changing state" },
      {
        kind: "list",
        items: [
          "Evaporation: a liquid slowly changes to vapour (wet clothes drying).",
          "Condensation: vapour cools back to liquid (water drops on a cold glass).",
          "Melting: solid → liquid; Freezing: liquid → solid.",
        ],
      },
      { kind: "heading", text: "The water cycle" },
      {
        kind: "para",
        text: "The Sun evaporates water from seas and rivers; the vapour rises, cools and condenses into clouds; it then falls as rain or snow and flows back — a never-ending cycle.",
      },
      { kind: "tip", text: "Evaporation happens at any temperature; boiling is fast evaporation at a fixed temperature (100°C for water)." },
    ],
  },
  {
    id: "6-chemistry-changes",
    classId: "6",
    subjectId: "chemistry",
    title: "Changes Around Us",
    blurb: "Reversible and irreversible changes in everyday life.",
    ncertRef: "NCERT Class 6 Science — Changes Around Us",
    lesson: [
      { kind: "heading", text: "Two kinds of change" },
      {
        kind: "para",
        text: "Things around us change all the time. Some changes can be undone; others cannot.",
      },
      {
        kind: "list",
        items: [
          "Reversible change: can be reversed to get back the original (melting ice, folding paper, stretching a rubber band).",
          "Irreversible change: cannot be undone (burning paper, cooking food, ripening a fruit).",
        ],
      },
      {
        kind: "example",
        problem: "Is melting of ice into water reversible?",
        solution: "Yes — cooling the water freezes it back into ice, so it is a reversible change.",
      },
      { kind: "tip", text: "If a brand-new substance forms (ash from burning), the change is usually irreversible." },
    ],
  },
  {
    id: "6-chemistry-air",
    classId: "6",
    subjectId: "chemistry",
    title: "Air Around Us",
    blurb: "What air is made of, and why oxygen matters.",
    ncertRef: "NCERT Class 6 Science — Air Around Us",
    lesson: [
      { kind: "heading", text: "Air is a mixture of gases" },
      {
        kind: "list",
        items: [
          "Nitrogen — about 78% (the largest part).",
          "Oxygen — about 21% (needed for breathing and burning).",
          "Carbon dioxide, water vapour and other gases — small amounts.",
        ],
      },
      { kind: "heading", text: "Why air matters" },
      {
        kind: "para",
        text: "Living things breathe in oxygen to release energy from food. Burning (combustion) also needs oxygen — that's why covering a flame, cutting off air, puts it out.",
      },
      { kind: "tip", text: "Plants release oxygen during photosynthesis, helping keep the air breathable." },
    ],
  },

  // ===================== BIOLOGY =====================
  {
    id: "6-biology-diversity",
    classId: "6",
    subjectId: "biology",
    title: "The Living World — Diversity & Characteristics",
    blurb: "Living vs non-living, characteristics of life, habitats and adaptation.",
    ncertRef: "NCERT Class 6 Science — Diversity / Living Creatures' Characteristics",
    lesson: [
      { kind: "heading", text: "What makes something living?" },
      {
        kind: "list",
        items: [
          "Growth and a definite life span.",
          "Need food (nutrition) and release energy (respiration).",
          "Respond to their surroundings (stimuli).",
          "Reproduce (produce young ones).",
          "Excrete waste and (most) show movement.",
        ],
      },
      { kind: "heading", text: "Habitats" },
      {
        kind: "para",
        text: "A habitat is the surrounding where an organism lives. Terrestrial habitats are on land (forests, deserts); aquatic habitats are in water (ponds, seas).",
      },
      {
        kind: "para",
        text: "Adaptations are special features that help an organism survive in its habitat — a fish has gills and fins, a camel stores fat in its hump for the desert.",
      },
      { kind: "tip", text: "A car moves and uses fuel, but it cannot grow or reproduce — so it is non-living." },
    ],
  },
  {
    id: "6-biology-nutrition",
    classId: "6",
    subjectId: "biology",
    title: "Components of Food (Nutrition)",
    blurb: "Nutrients, a balanced diet, and deficiency diseases.",
    ncertRef: "NCERT Class 6 Science — Mindful Eating / Components of Food",
    lesson: [
      { kind: "heading", text: "The main nutrients" },
      {
        kind: "list",
        items: [
          "Carbohydrates — main energy food (rice, bread, potato).",
          "Fats — store extra energy (oil, butter, nuts).",
          "Proteins — body-building (pulses, eggs, milk, meat).",
          "Vitamins and minerals — protect the body and keep it healthy.",
          "Roughage (fibre) and water — help digestion.",
        ],
      },
      { kind: "heading", text: "Balanced diet" },
      {
        kind: "para",
        text: "A balanced diet has the right amount of all nutrients. Missing a nutrient for long causes a deficiency disease — too little vitamin C causes scurvy; too little iron causes anaemia.",
      },
      { kind: "tip", text: "Carbohydrates and fats are 'energy-giving'; proteins are 'body-building'; vitamins/minerals are 'protective'." },
    ],
  },
  {
    id: "6-biology-food-sources",
    classId: "6",
    subjectId: "biology",
    title: "Food: Where Does It Come From?",
    blurb: "Plant and animal sources of food, and eating habits of animals.",
    ncertRef: "NCERT Class 6 Science — Food: Where Does it Come From",
    lesson: [
      { kind: "heading", text: "Sources of food" },
      {
        kind: "para",
        text: "Our food comes from plants (fruits, vegetables, grains, pulses) and animals (milk, eggs, meat, honey). Different parts of plants are eaten — roots (carrot), leaves (spinach), seeds (rice), fruits (mango).",
      },
      { kind: "heading", text: "Animals by what they eat" },
      {
        kind: "list",
        items: [
          "Herbivores eat only plants (cow, goat).",
          "Carnivores eat other animals (lion, tiger).",
          "Omnivores eat both plants and animals (humans, crow).",
        ],
      },
      {
        kind: "example",
        problem: "A cow eats only grass. What is it called?",
        solution: "An animal that eats only plants is a herbivore.",
      },
    ],
  },
  {
    id: "6-biology-plants",
    classId: "6",
    subjectId: "biology",
    title: "Getting to Know Plants",
    blurb: "Parts of a plant and their functions; types of plants.",
    ncertRef: "NCERT Class 6 Science — Getting to Know Plants",
    lesson: [
      { kind: "heading", text: "Parts of a plant" },
      {
        kind: "list",
        items: [
          "Roots: anchor the plant and absorb water and minerals from the soil.",
          "Stem: holds the plant up and carries water and food.",
          "Leaves: make food using sunlight (photosynthesis) — the kitchen of the plant.",
          "Flower: the reproductive part, which becomes fruit and seeds.",
        ],
      },
      { kind: "heading", text: "Types of plants" },
      {
        kind: "para",
        text: "Herbs are small and soft; shrubs are bushy with woody stems; trees are tall with a thick, hard trunk.",
      },
      { kind: "tip", text: "Tiny pores on leaves (stomata) let gases in and out and release water vapour (transpiration)." },
    ],
  },
  {
    id: "6-biology-body-movements",
    classId: "6",
    subjectId: "biology",
    title: "Body Movements",
    blurb: "The skeleton, joints, and how animals move.",
    ncertRef: "NCERT Class 6 Science — Body Movements",
    lesson: [
      { kind: "heading", text: "Bones and the skeleton" },
      {
        kind: "para",
        text: "The framework of bones in our body is the skeleton. It gives the body shape and support and protects soft organs (the skull guards the brain, the ribs guard the heart and lungs).",
      },
      { kind: "heading", text: "Joints" },
      {
        kind: "list",
        items: [
          "Ball-and-socket joint: rotation in many directions (shoulder, hip).",
          "Hinge joint: back-and-forth like a door (elbow, knee).",
          "Pivot joint: lets the head turn (neck).",
          "Fixed joint: no movement (bones of the skull).",
        ],
      },
      {
        kind: "para",
        text: "Muscles work in pairs to move bones — one contracts (shortens) to pull the bone while the other relaxes.",
      },
      { kind: "tip", text: "A bone cannot push — that's why muscles work in pairs to move it both ways." },
    ],
  },
];

export const C6_SCIENCE_QUESTIONS: Question[] = [
  // Magnets
  {
    id: "q-6s-mag-1",
    chapterId: "6-physics-magnets",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which material is attracted by a magnet?",
    options: ["wood", "iron", "plastic", "rubber"],
    answer: "iron",
    solution: "Iron (along with nickel and cobalt) is a magnetic material; the others are non-magnetic.",
  },
  {
    id: "q-6s-mag-2",
    chapterId: "6-physics-magnets",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "medium",
    prompt: "When two north poles of magnets are brought close, they:",
    options: ["attract", "repel", "do nothing", "stick together"],
    answer: "repel",
    solution: "Like poles (N–N or S–S) repel each other; only unlike poles attract.",
  },
  {
    id: "q-6s-mag-3",
    chapterId: "6-physics-magnets",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "easy",
    prompt: "A freely suspended bar magnet always comes to rest pointing:",
    options: ["east–west", "north–south", "up–down", "randomly"],
    answer: "north–south",
    solution: "This north–south alignment is the principle behind a compass.",
  },

  // Temperature
  {
    id: "q-6s-temp-1",
    chapterId: "6-physics-temperature",
    classId: "6",
    subjectId: "physics",
    type: "numeric",
    difficulty: "easy",
    prompt: "The normal temperature of the human body is about ___ °C.",
    answer: "37",
    solution: "A healthy human body is around 37°C.",
  },
  {
    id: "q-6s-temp-2",
    chapterId: "6-physics-temperature",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which instrument measures temperature?",
    options: ["ruler", "thermometer", "balance", "compass"],
    answer: "thermometer",
    solution: "A thermometer measures temperature in degrees Celsius (°C).",
  },

  // Light, Shadows
  {
    id: "q-6s-light-1",
    chapterId: "6-physics-light-shadows",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which of these is a luminous object?",
    options: ["the Moon", "a mirror", "the Sun", "a book"],
    answer: "the Sun",
    solution: "The Sun gives out its own light, so it is luminous. The Moon only reflects sunlight.",
  },
  {
    id: "q-6s-light-2",
    chapterId: "6-physics-light-shadows",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "medium",
    prompt: "An object through which no light can pass is called:",
    options: ["transparent", "translucent", "opaque", "luminous"],
    answer: "opaque",
    solution: "Opaque objects block light completely and form shadows.",
  },

  // Electricity
  {
    id: "q-6s-elec-1",
    chapterId: "6-physics-electricity",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which of these is a good conductor of electricity?",
    options: ["rubber", "copper", "plastic", "wood"],
    answer: "copper",
    solution: "Metals like copper conduct electricity; rubber, plastic and wood are insulators.",
  },
  {
    id: "q-6s-elec-2",
    chapterId: "6-physics-electricity",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "medium",
    prompt: "A bulb glows only when the circuit is:",
    options: ["open", "closed", "broken", "switched off"],
    answer: "closed",
    solution: "A closed (complete) circuit lets electricity flow, so the bulb lights up.",
  },

  // Beyond Earth
  {
    id: "q-6s-be-1",
    chapterId: "6-physics-beyond-earth",
    classId: "6",
    subjectId: "physics",
    type: "numeric",
    difficulty: "easy",
    prompt: "How many planets are there in our solar system?",
    answer: "8",
    solution: "There are eight planets, from Mercury to Neptune.",
  },
  {
    id: "q-6s-be-2",
    chapterId: "6-physics-beyond-earth",
    classId: "6",
    subjectId: "physics",
    type: "mcq",
    difficulty: "medium",
    prompt: "The planet closest to the Sun is:",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    answer: "Mercury",
    solution: "Mercury is the innermost planet, closest to the Sun.",
  },

  // Materials
  {
    id: "q-6s-mat-1",
    chapterId: "6-chemistry-materials",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which substance is soluble in water?",
    options: ["sand", "chalk powder", "sugar", "oil"],
    answer: "sugar",
    solution: "Sugar dissolves in water (soluble); sand and chalk are insoluble and oil does not mix.",
  },
  {
    id: "q-6s-mat-2",
    chapterId: "6-chemistry-materials",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "medium",
    prompt: "A material you can see through clearly is called:",
    options: ["opaque", "transparent", "lustrous", "soluble"],
    answer: "transparent",
    solution: "Transparent materials (like clear glass) let light pass through so you can see through them.",
  },

  // Separation
  {
    id: "q-6s-sep-1",
    chapterId: "6-chemistry-separation",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "medium",
    prompt: "Which method separates sand from water?",
    options: ["winnowing", "filtration", "handpicking", "sieving"],
    answer: "filtration",
    solution: "Sand is insoluble, so filtration traps it while clear water passes through.",
  },
  {
    id: "q-6s-sep-2",
    chapterId: "6-chemistry-separation",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "medium",
    prompt: "Separating heavier grain from lighter husk using wind is called:",
    options: ["sieving", "filtration", "winnowing", "decantation"],
    answer: "winnowing",
    solution: "Winnowing uses wind (or a fan) to blow away the lighter husk.",
  },

  // States of Water
  {
    id: "q-6s-wat-1",
    chapterId: "6-chemistry-states-of-water",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "medium",
    prompt: "Water vapour changing back into liquid water is called:",
    options: ["evaporation", "condensation", "melting", "freezing"],
    answer: "condensation",
    solution: "Condensation is gas → liquid, like water drops forming on a cold glass.",
  },
  {
    id: "q-6s-wat-2",
    chapterId: "6-chemistry-states-of-water",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "easy",
    prompt: "Wet clothes drying in the sun is an example of:",
    options: ["condensation", "evaporation", "freezing", "melting"],
    answer: "evaporation",
    solution: "Liquid water slowly turns to vapour and leaves the clothes — evaporation.",
  },

  // Changes
  {
    id: "q-6s-chg-1",
    chapterId: "6-chemistry-changes",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which is a reversible change?",
    options: ["burning paper", "cooking food", "melting ice", "ripening a fruit"],
    answer: "melting ice",
    solution: "Melted ice can be frozen back into ice, so it is reversible. The others form new substances.",
  },
  {
    id: "q-6s-chg-2",
    chapterId: "6-chemistry-changes",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "medium",
    prompt: "Which of these is an irreversible change?",
    options: ["folding paper", "burning wood", "stretching a band", "melting wax"],
    answer: "burning wood",
    solution: "Burning produces ash and gases that cannot become wood again — irreversible.",
  },

  // Air
  {
    id: "q-6s-air-1",
    chapterId: "6-chemistry-air",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "medium",
    prompt: "Which gas makes up most of the air (about 78%)?",
    options: ["oxygen", "carbon dioxide", "nitrogen", "hydrogen"],
    answer: "nitrogen",
    solution: "Air is about 78% nitrogen and 21% oxygen.",
  },
  {
    id: "q-6s-air-2",
    chapterId: "6-chemistry-air",
    classId: "6",
    subjectId: "chemistry",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which gas is needed for burning?",
    options: ["nitrogen", "oxygen", "carbon dioxide", "helium"],
    answer: "oxygen",
    solution: "Burning needs oxygen; cutting off air puts out a flame.",
  },

  // Diversity
  {
    id: "q-6s-div-1",
    chapterId: "6-biology-diversity",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which is a characteristic of all living things?",
    options: ["they are made of metal", "they reproduce", "they never move", "they don't need food"],
    answer: "they reproduce",
    solution: "Living things grow, need food, respond, reproduce and excrete.",
  },
  {
    id: "q-6s-div-2",
    chapterId: "6-biology-diversity",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "medium",
    prompt: "A pond is an example of which habitat?",
    options: ["terrestrial", "aquatic", "desert", "forest"],
    answer: "aquatic",
    solution: "Aquatic habitats are in water, like ponds, lakes and seas.",
  },

  // Nutrition
  {
    id: "q-6s-nut-1",
    chapterId: "6-biology-nutrition",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which nutrient is the main 'body-building' food?",
    options: ["carbohydrates", "fats", "proteins", "water"],
    answer: "proteins",
    solution: "Proteins (pulses, eggs, milk) build and repair the body.",
  },
  {
    id: "q-6s-nut-2",
    chapterId: "6-biology-nutrition",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "medium",
    prompt: "Deficiency of vitamin C causes:",
    options: ["scurvy", "anaemia", "night blindness", "rickets"],
    answer: "scurvy",
    solution: "Too little vitamin C causes scurvy (bleeding gums).",
  },

  // Food sources
  {
    id: "q-6s-food-1",
    chapterId: "6-biology-food-sources",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "easy",
    prompt: "An animal that eats only plants is called a:",
    options: ["carnivore", "herbivore", "omnivore", "predator"],
    answer: "herbivore",
    solution: "Herbivores (cow, goat) eat only plants.",
  },
  {
    id: "q-6s-food-2",
    chapterId: "6-biology-food-sources",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which food comes from an animal source?",
    options: ["rice", "milk", "wheat", "mango"],
    answer: "milk",
    solution: "Milk comes from animals (cow, buffalo, goat); the others are from plants.",
  },

  // Plants
  {
    id: "q-6s-pl-1",
    chapterId: "6-biology-plants",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which part of a plant makes food?",
    options: ["root", "stem", "leaf", "flower"],
    answer: "leaf",
    solution: "Leaves make food by photosynthesis using sunlight.",
  },
  {
    id: "q-6s-pl-2",
    chapterId: "6-biology-plants",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "easy",
    prompt: "Which part anchors the plant and absorbs water?",
    options: ["leaf", "flower", "root", "fruit"],
    answer: "root",
    solution: "Roots fix the plant in the soil and absorb water and minerals.",
  },

  // Body Movements
  {
    id: "q-6s-bm-1",
    chapterId: "6-biology-body-movements",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "medium",
    prompt: "Which joint is found at the elbow?",
    options: ["ball-and-socket", "hinge", "pivot", "fixed"],
    answer: "hinge",
    solution: "The elbow is a hinge joint, allowing back-and-forth movement like a door.",
  },
  {
    id: "q-6s-bm-2",
    chapterId: "6-biology-body-movements",
    classId: "6",
    subjectId: "biology",
    type: "mcq",
    difficulty: "medium",
    prompt: "The shoulder has which type of joint?",
    options: ["hinge", "fixed", "ball-and-socket", "pivot"],
    answer: "ball-and-socket",
    solution: "The ball-and-socket joint at the shoulder allows movement in many directions.",
  },
];
